### ISSUE TITLE
detection_output.cc is missing

### ISSUE THREAD

**Issue by justmyfantasy** [XiaoMi/mace-models#12]
I wonder where can I find detection_output.cc or any other examples showing how to use the converted mobilenet-ssd model?

**Comment by lydoc** [comment]
Since detection output is belonging to the post-processing part, we removed detection_output.cc in the latest version of mace. But you can also refer to the [previous code](https://github.com/XiaoMi/mace/blob/v0.10.0/mace/utils/detection_output.cc). Also, you can refer to this [issue](https://github.com/XiaoMi/mace/issues/309#issuecomment-455051042) for using the converted model.

**Comment by justmyfantasia** [comment]
> Since detection output is belonging to the post-processing part, we removed detection_output.cc in the latest version of mace. But you can also refer to the [previous code](https://github.com/XiaoMi/mace/blob/v0.10.0/mace/utils/detection_output.cc). Also, you can refer to this [issue](https://github.com/XiaoMi/mace/issues/309#issuecomment-455051042) for using the converted model.

Thanks! I'll check that out.
